### ISSUE TITLE
Validate that a pokemon can be played from the deck list

### ISSUE THREAD

**Issue by DrunkDutch** [DrunkDutch/comp-354#40]
Ensure that a non-basic pokemon can be played (IE: required basic pokemon is included in the decklist)
Required for #39  and #2  story

**Comment by Spun-G** [comment]
[PokemonPlayabilityValidation](https://github.com/DrunkDutch/comp-354/tree/PokemonPlayabilityValidation) has work done for this, though the test files need updating. It doesn't look like the valid deck passes the test due to there only being water-type energy cards included, but Machop's Knuckle Punch ability needs fighting-type energy to be considered playable.

**Comment by Spun-G** [comment]
so the valid deck would fail a "no more than 4 of a non-energy card" requirement if that were tested but wtv everything else seems to be validated; as far as this issue is concerned the task is complete and the issue can be closed after a merge
